#!/usr/bin/with-contenv bash

set_crontab() {
    echo "Set crontab to system..."
    echo "* * * * * php $WORKDIR/do.php" | crontab -
}

set_crontab 2>&1 | sed "s#^#[cont-init.d] $(basename $0): \1#g"