DROP TABLE IF EXISTS `{VAR-PREFIX}cron`;
DROP TABLE IF EXISTS `{VAR-PREFIX}options`;
DROP TABLE IF EXISTS `{VAR-PREFIX}tieba`;
DROP TABLE IF EXISTS `{VAR-PREFIX}users`;
DROP TABLE IF EXISTS `{VAR-PREFIX}users_options`;
DROP TABLE IF EXISTS `{VAR-PREFIX}baiduid`;
DROP TABLE IF EXISTS `{VAR-PREFIX}plugins`;